name: valéeéternelle
favicon: null
layout_spectrum: 0.8081709134858102
typography_spectrum: 0.46095415973104537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.20058236387558281
  lightness: 0.5262035091873258
  saturation: 0.4292957694269717
  rhythmicContrast: 0.2573726095724851
purpose: []
